### ISSUE TITLE
EA7500v2 WiFi不能分配ip

### ISSUE THREAD

**Issue by redfrog999** [padavanonly/immortalwrt#30]
拉源码为EA7500v2生成了一个固件，各方面都很好，就是WiFi在刚刷机和重置后不能自动分配IP，不论是2.4g还是5g都是这样，必须要把原来的配置etc/network传上去重启才能正常分配IP。希望大佬能适配下ea7500v2，不胜感激。

**Comment by GreyFlorence** [comment]
我用 Xiaomi R3G也遇到了同样的问题，修改etc/network并重启后，wifi便无法分配IP。请问你的问题解决了吗？

**Comment by redfrog999** [comment]
> 我用 Xiaomi R3G也遇到了同样的问题，修改etc/network并重启后，wifi便无法分配IP。请问你的问题解决了吗？

我的是刷机后不能分配IP，但是手动修改/ect/config/network后就正常使用了。

**Comment by zow2023** [comment]
朋友  用的源码怎样给ea8100 云编译一个固件啊  本人很白菜 能说下大概的步骤吗

**Comment by redfrog999** [comment]
> 朋友 用的源码怎样给ea8100 云编译一个固件啊 本人很白菜 能说下大概的步骤吗

上油管找视频看看学习一下，一下说不清。

**Comment by zow2023** [comment]
其他我都知道了 就是不知道咋改代码-- 7xxx.dts和02_network这两个文件 你的源码是已经改好了的吗？因为我看你编好了ea7500v2的固件  我想开启SDK.HNAT 还望不吝赐教

**Comment by redfrog999** [comment]
> 其他我都知道了 就是不知道咋改代码-- 7xxx.dts和02_network这两个文件 你的源码是已经改好了的吗？因为我看你编好了ea7500v2的固件 我想开启SDK.HNAT 还望不吝赐教

我改好的是7500v2的，你的机型要自己适配。

**Comment by zow2023** [comment]
这两台机器的配置是一样的 你编的我强刷也是可以用的 但是我下午用你的源码编译了一次 无线连接还是分配IP地址   具体是怎么改  真心搞不定了  我认为你的源码是已经修改好了的  对不？

**Comment by zow2023** [comment]
感谢  搜了下基本知识  在你的基础上改了一下  就可以了  感谢分享  感谢大家

**Comment by redfrog999** [comment]
能用上就好，我打算改改内存继续玩。哈哈

**Comment by zow2023** [comment]
朋友 你加的那个超频补丁有效果没 我也想试一下，，。

**Comment by redfrog999** [comment]
小心，可能会有奇奇怪怪的问题，我就遇到突然就没法上网也不能进后台了。不同commit的表现不一样，而且237的源码性能跑分偏低，超频后提升不是很明显。

**Comment by zow2023** [comment]
我完全copy你的提交过来 跑了个ea8100的固件  我用几天跟你反馈 有无奇怪问题出现 看他们在小米路由商店表现不错 为什么在领势上就提升不明显了呢？

**Comment by redfrog999** [comment]
你跑下Openssl看看分数，我的237源码超频后多核是这个分数：
evp              13925.08k    15220.07k    15600.40k    15667.54k    15673.66k    15638.28k
但是在开源固件是这个分数：
evp              14965.33k    16936.27k    17539.91k    17677.10k    17742.08k    17728.47k

你跑下8100看看怎么样。

**Comment by zow2023** [comment]
转换5G 到2.4的时候 断网  不能登录管理界面  我缺少组件不能直接跑分 在237的源码刷的固件下  我用lienol的21.02的固件跑的分是
 chacha20-poly1305    10076.03k    16774.63k    19536.47k    20313.09k    20630.19k    20520.82k

**Comment by redfrog999** [comment]
poly1305加密方式算是7621的强项了，只有Openssl让7621显得很落后了。如果你手头的7621超到1.1g不稳就要降到1g，再不行就要回到默认了。默认的反应速度还是相比1.1g慢了不少，网络应用方面如果不是跑翻墙插件其实提升不是很大。

你需要Openssl-util这个插件就能openssl跑分了。你可以去这里下载。https://op.supes.top/packages/mipsel_24kc/

**Comment by zow2023** [comment]
用的是这道命令吗-openssl speed -evp aes-256-gcm ？ 超频的固件问题是遇到5G换2.4 会掉线2分钟左右啊  网络全无 不能登管理界面，问题是电脑上的WiFi标识还是一样的  你遇见这样的问题吗？

**Comment by zow2023** [comment]
没超频237源码的固件aes-256-gcm       4722.07k     5162.64k     5283.33k     5313.88k     5309.83k     5330.26k   7500v2的

**Comment by redfrog999** [comment]
> 用的是这道命令吗-openssl speed -evp aes-256-gcm ？ 超频的固件问题是遇到5G换2.4 会掉线2分钟左右啊 网络全无 不能登管理界面，问题是电脑上的WiFi标识还是一样的 你遇见这样的问题吗？

我遇到的是直接断网死机了。网络切换倒是很顺畅，但是Ax200跟发哥有冲突，会断连三次才能稳定连上路由器，不管是5g还是2g。我的237源码固件超频到1.1g跑poly1305是这个分数：

type                              16 bytes     64 bytes    256 bytes   1024 bytes   8192 bytes  16384 bytes
chacha20-poly1305    12855.42k    21241.24k    24524.37k    25482.19k    25808.88k    25316.27k

看来lienol的源码跟237的各有所长。
