### ISSUE TITLE
newifi-d2 compile error

### ISSUE THREAD

**Issue by Cathgao** [padavanonly/immortalwrt#43]
```
error: ../dts/mt7621_lenovo_newifi-d1.dts:154.97-98 syntax error
FATAL ERROR: Unable to parse input tree
```
[log1.log](https://github.com/padavanonly/immortalwrt/files/14061703/log1.log)
[config_D2.txt](https://github.com/padavanonly/immortalwrt/files/14061711/config_D2.txt)

**Comment by Cathgao** [comment]
是删掉整个文件夹重新拉取仓库之后编译的

**Comment by seiry** [comment]
same issue

**Comment by Cathgao** [comment]
fixed
