### ISSUE TITLE
feeds文件835行错误"Can't exec "": No such file or directory at ./scripts/feeds line 835."

### ISSUE THREAD

**Issue by NayaCcR** [padavanonly/immortalwrt#47]
在重新clone本项目后执行`` ./scripts/feeds update -a ``时
出现`
``` bash
Can't exec "": No such file or directory at ./scripts/feeds line 835.
```
错误
运行`` ./scripts/feeds install -a`` 时
均出现
``` bash 
ln: failed to create symbolic link './package/feeds/packages/': No such file or directory
Installing package 'redsocks2' from packages
```
同类型的报错

**Comment by mookixiao** [comment]
我也出现了Can't exec "": No such file or directory at ./scripts/feeds line 835.
请问解决了吗？

**Comment by NayaCcR** [comment]
答案是没有，貌似是padavanonly仓库源码的问题？我最后用了别的大佬的scripts/feeds部分替代了这个仓库里的feeds，我有计划去看padavan大佬那里有问题来着，等我回复

**Comment by jackcctse** [comment]
用ubuntu 18.04好像沒有这个報錯。

**Comment by mookixiao** [comment]
> 我也出现了Can't exec "": No such file or directory at ./scripts/feeds line 835. 请问解决了吗？

问题解决，按照楼上说的使用ubuntu 18.04编译就可以
